### PR TITLE
Function gaze pointer

### PR DESCRIPTION
**Pull request by surreal6**
A new implementation of the Gaze Pointer but as an independent function. Based in #664 PR

With 'click on hold' boolean you can select to send clicks to the target node or just move the mouse around.

### CODE REVIEW

**Comment by Malcolmnixon** [comment]
This is looking very good - although it did highlight a bug with the desktop integration overwriting the headset rotation even in full XR mode - https://github.com/GodotVR/godot-xr-tools/issues/684

Do you think it's beneficial to keep the laser functionality - it can be enabled and does work, but it looks so bad (the laser coming out between the eyes) I'm not sure it'd ever want to be enabled.

**Comment by surreal6** [comment]
Oh, good, you found the bug with the desktop integration. I was unable to detect where it came from, but was suspecting from desktop integration and asked pietru about, but he didn't see any bug... 

Yes, i think we can remove the laser functionality.  As i understand, It its useful just to check if the pointer is working, but you can also use the target for this. I can remove the laser functionality for clearness.

**Comment by surreal6** [comment]
this will fix #662 issue

**Comment by RangerMauve** [comment]
TY for working on this!

**Comment by Malcolmnixon** [comment]
With Pietru's fix this now works perfectly.

**Review by Malcolmnixon — APPROVED** [review]
This works very well. Nice job

**Pull request merged**
