### PR TITLE
Create editor icons

### LINKED ISSUE #172: Add Editor Icons to XRTool nodes
So it's not just the default circle.

And Obviously, following the advice / tool workflow set out in [docs:Editor Icons](https://docs.godotengine.org/en/latest/development/editor/creating_icons.html)

### PR DESCRIPTION
**Pull request by lunarcloud**
To resolve #172 

image

### CODE REVIEW

**Comment by lunarcloud** [comment]
I made the common element the "XR *monkeywrench"
image

**Comment by lunarcloud** [comment]
and yeah, I beleive I've run svgcleaner on all the icons I included ([as recommended](https://docs.godotengine.org/en/latest/development/editor/creating_icons.html#icon-optimization)).

**Comment by BastiaanOlij** [comment]
This is very cool! Might be nice if you could squash the commits to a single commit.

**Review by BastiaanOlij — APPROVED** [review]
Don't forget to add your name to Contributors.md file :)

**Comment by lunarcloud** [comment]
I'll figure out how to squash pre-commit soonish.
And yeah, CC0 is very cool with me. 
Am already in the contributors for something I did with Malcolm.

**Comment by lunarcloud** [comment]
Okay, happy with this.
@BastiaanOlij  I hope the license file is in the right location

**Comment by lunarcloud** [comment]
Just noticed inconsistency I need to fix...
image

**Comment by lunarcloud** [comment]
image

Monkeywrench ( / Clamp?) symbol fixed for all

**Comment by lunarcloud** [comment]
I have utterly failed to figure out how to pre-squash this...
but you can squash merge these right?

image

If you like,  I can re-fork and commit as a single change.

**Comment by BastiaanOlij** [comment]
No worries man, I'll take care of the squashing, just need to find some time for it tonight.

**Comment by BastiaanOlij** [comment]
Ah, I see where you made your life hard, you made the changes directly on your 2.x branch. Always create a new branch to do your development in, you're going to have a tough time getting 2.x updated once we merge

**Comment by BastiaanOlij** [comment]
I've resubmitted this under https://github.com/GodotVR/godot-xr-tools/pull/174 and merged it.

You might want to double check if I didn't mess up an icon, not sure how you managed it Sam but it was a PITA to rebase and squash:)

Because you've modified your 2.x branch you'll have trouble pulling things. You will want to do the following steps.

If you haven't already added upstream:
```
git remote add upstream https://github.com/GodotVR/godot-xr-tools
```

Then:
```
git branch -m 2.x 2.x_old
git fetch upstream
git checkout upstream/2.x
git switch -c 2.x
git push origin 2.x -f
git branch -D 2.x_old
```

I advise making a backup of your folder.

**Pull request closed without merging**
