### PR TITLE
Flapping wings. Add vertical impulse when flapping arms

### PR DESCRIPTION
**Pull request by surreal6**
This PR adds a new option to the movement_glide script. It adds a vertical impulse when flapping your arms. The impulse is relative to the downwards velocity of the controllers.

It has a boolean 'wings_impulse' to activate the feature (default is set to false)
It also has an exported 'wings_force' variable to multiply the vertical impulse.

Also added some floating rings to the glide scene to play fly through them.

### CODE REVIEW

**Comment by Malcolmnixon** [comment]
I *REALLY* like it - it's definitely lots of fun, if not tiring on the arms - and I made a game last year where you could turn into a bird, but I only had the gliding ;)

I think you need to add a "flapped" signal which you fire when you detect the player flap their arms - a game would want to subscribe to it and play a bird-flap sound to go along with the arm movements. To do that without glitching, you'd need to improve the flap detection - possibly reporting when both hands are moving down quickly (greater than 0.3 m/s) and then require both hands to go up before re-arming.

**Comment by surreal6** [comment]
ok, thats a good idea. I'll try.

Maybe i can activate the wings only when both controllers are above the head.

One question, where do i find the gdlint specification for this repo? Do you know if there is an eslint plugin for gdscript in visual studio?

**Comment by Malcolmnixon** [comment]
The gdlint project is at https://github.com/Scony/godot-gdscript-toolkit and has the installation and running instructions.

It enforces the coding style from https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html

You can also see the issues list in this pull request page, although it's obviously better to fix them before pushing.

**Comment by surreal6** [comment]
i have the logic working :)  

need to check the lint stuff. Will do it in the next days.

Also, can update the docs for the glide movement in this same PR if you prefer.

**Comment by BastiaanOlij** [comment]
@surreal6 docs are in a separate branch so it'll have to be a separate PR.

**Review by BastiaanOlij — APPROVED** [review]
Cool addition, can be merged after lint issues are resolved and if Malcolm hasn't any further wishes for improvements.

Also don't forget to add your name to contributors.md

**Comment by Malcolmnixon** [comment]
I need to do some additional checks on this. Originally glide only fired when you were "falling", so for example a jump-pad would throw you into the air, but you couldn't glide until you reached the maximum height and started falling back down.

You removed the falling check (because flapping involves moving the player up), however we may want to restore that condition if flapping is disabled.

I may need to add a jump-pad or two to the gliding demo scene to verify functionality. Also the gliding demo should probably prevent the player from flying too far (disable flapping if the player is above the top of the cliffs) otherwise the player will be able to fly/glide off the edge of the world.

**Comment by surreal6** [comment]
Check it and tell me! 

Please note I didn't remove the falling check, but split it in two different checks:

```
if player_body.on_ground:
		_set_gliding(false)
		return
var wings_impulse_velocity := 0.0

if wings_impulse:
		** here i calculate the wings impulse
		** and after that: 

if vertical_velocity >= glide_min_fall_speed && wings_impulse_velocity == 0.0:
		_set_gliding(false)
		return
```

With this, if you jump and make a strong flap at the same time, you can take off, but if you are not flapping, it works the same as before (as i understand, maybe i'm wrong)

To put a limit to the flying altitude is a good idea.

**Comment by Malcolmnixon** [comment]
There still might be some future enhancements that can be added - for example supporting roll-turning while flapping - currently the moment the player flaps, the player starts moving up and so the roll-turning shuts off.

**Pull request merged**
