### PR TITLE
Add smooth player height control

### PR DESCRIPTION
**Pull request by Malcolmnixon**
This pull request cleans up crouching and fixes issues #384 and #480 by:
- Smoothly blending between player-controlled-height and software-override-height.
- Block player-height from growing when blocked by a low ceiling.

The following video demonstrates its behavior in the test scenes - https://youtu.be/D43q14dIUKc

### CODE REVIEW

**Review by DigitalN8m4r3 — APPROVED** [review]
**_Tested this in and out as it delivers a much needed feature that the XR Tools are lacking_**

*a way to prevent the players head from moving thru ceilings and blockade spots

Now this PR adds the above and some more as it accounts for the physical height change when the player suddenly stands up, the effect ingame is that the player is still under the blockade spot. 

I might be biased as i was working on and off on a way to do just that but was to much locked in the idea of inducing a motion sickness way to do this, however since i had the chance to test this implementation and compare it to similar ideas in unity, i can say that this is it. It works and accounts for sitting/standing up and vice versa without breaking the immersion.

One thing i would like to request would be to add this to the possible 2.1 HotFix as it paths the way for other things such as the Seating PR #462 to work in a more homogeneous way

**Comment by pietru2004** [comment]
I don't see much problems althrou the hand gui could have box for making finger straight, I keep bumping into my hand with it nor straight, well I guess it is not from this merge req...
Also I couldn't see problems with height ovverride change and the low celing worked and did not make my cam go throu it

**Review by pietru2004 — APPROVED** [review]
👍

**Review by BastiaanOlij — APPROVED** [review]
lgtm, but needs testing!

**Comment by Malcolmnixon** [comment]
Added a YouTube video showing the new behavior.

**Comment by GreenboxGames** [comment]
I can confirm this fixes my issue #480 with both plane collisions and terrain collisions. However, if I jump while uncrouching, it seems to have the side effect of jump boosting when you jump while uncrouching. This could be a feature, but not in all cases of controller.

**Comment by Malcolmnixon** [comment]
I tracked down the jump-boosting to a double-jump and prevented it with a better "standing on the ground" test.

**Comment by DigitalN8m4r3** [comment]
lgtm, no double jump noticed :)

**Pull request merged**
