### PR TITLE
Added initial support for swapping items between hands

### PR DESCRIPTION
**Pull request by Malcolmnixon**
This pull request allows swapping items between hands. This also supports having multiple grab-points and finding the best one based on distance and grab-rules. These changes will also be necessary when implementing two-handed grabs.

### CODE REVIEW

**Comment by DigitalN8m4r3** [comment]
for a brainstorm result, not bad

In fact these changes path the way for more ambitious stuff such as twohanded. 
First tests looking good so far. 
Will comment on further updates, nice one @Malcolmnixon

**Comment by DigitalN8m4r3** [comment]
alright i added the changes to the interactable_handle i had done in my initial collision hands pr and it almost gets the job done now with the above

as can be seen in the video, i have attached the edited files for testing purposes and evaluation/debugging

https://github.com/GodotVR/godot-xr-tools/assets/56046022/64e5dcc3-8a2e-493a-8785-fbb4ae7b552b

[twohanded_bugged.zip](https://github.com/GodotVR/godot-xr-tools/files/13244380/twohanded_bugged.zip)

**Comment by Malcolmnixon** [comment]
The following video shows the new multiple-grab-points feature. The hammer has two sets of grab points - currently both are configured for "General" grabbing so a pickup just uses the closest one.

https://github.com/GodotVR/godot-xr-tools/assets/1863707/183ae549-1050-4f87-b87b-d38b0b386334

**Comment by DigitalN8m4r3** [comment]
lgtm,
multiple grab points work pretty good, there is not much else to say, the video above shows its functionality

**Review by BastiaanOlij — APPROVED** [review]
lgtm, works like a charm, I think we can get through the breakage.

**Pull request merged**
