### PR TITLE
added rumble manager and demo

### PR DESCRIPTION
**Pull request by lunarcloud**
Implement #191

### CODE REVIEW

**Comment by lunarcloud** [comment]
Feel free to be brutal. I'd rather have it right.

Also, I did not implement rumbling across the functions of the toolkit (didn't know whether that should be in here or later) just in the demo.

**Comment by lunarcloud** [comment]
@Malcolmnixon wants me to create a sort of "Rumble Player" to that can find the rumble manager, and provide a means to add rumble to any function/gun/etc

**Comment by lunarcloud** [comment]
After more discussion with @Malcolmnixon I will be making the rumble manager a singleton which "XRToolRumbleFeature"s added to the hands will ensure exist. This Singleton will be easier to access from scripts that want to make rumbling happen.

**Comment by BastiaanOlij** [comment]
I had forgotten how primitive haptics are implemented in Godot 3 :)

At first glance I think I get the idea behind this and it seems a good approach, I'll have to find some more time to actually experiment with it.

This is the kind of enhancement that could use more detail in the OP to explain what is being added and how its supposed to be used from a user point of view (i.e. someone making a game).

**Comment by BastiaanOlij** [comment]
Quick discussion in XR meeting about this as we'd like to move forward with this PR. Need to get input from more XR tool users what they are expecting out of rumble and whether this is a solution they agree with.

Would love everyones feedback.

@lunarcloud would you mind rebasing this so that the merge issues are resolved so people can test?

**Comment by lunarcloud** [comment]
Superceded by #557

**Pull request closed without merging**
